robotType: "panda_wristcam" 
replaySaveDir: "/home/normansmith/blue_storage/projects/Online-Diffusion-Policy/data"

baseEnvironment:
  numEnvironments: 512
  obsMode: "rgbd"
  rewardType: "dense"
  renderMode: "rgb_array"
  simBackend: "gpu"
  sensorSize: 
    height: 224
    width: 224

timeHorizon: 32 

noiseStats: 
  distribution: "logitNormal"
  shift: 0.2
  mean: 0
  std: 0.05
  
envs:
  - LiftPegUpright-v1
  - PegInsertionSide-v1
  - PickCube-v1
  - PlugCharger-v1
  - PokeCube-v1
  - PullCube-v1
  - PullCubeTool-v1
  - PushCube-v1
  - PushT-v1
  - RollBall-v1
  - StackCube-v1
  - StackPyramid-v1